name: Build iOS ESP
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Theos Compiler
        run: |
          bash -c "$(curl -fsSL https://githubusercontent.com)"
          echo "THEOS=~/theos" >> $GITHUB_ENV

      - name: Compile Dylib
        run: |
          make ARCHS="arm64" TARGET="iphone:clang:latest:14.0"
          
      - name: Upload Ready Dylib
        uses: actions/upload-artifact@v4
        with:
          name: MyCleanESP
          path: .theos/obj/debug/*.dylib
