name: Build iOS ESP
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-13
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Theos environment variables
        run: |
          echo "THEOS=/Users/runner/theos" >> $GITHUB_ENV

      - name: Install Theos Framework
        run: |
          git clone --recursive https://github.com /Users/runner/theos
          curl -LO https://github.com
          tar -xf iPhoneOS14.5.sdk.tar.xz -C /Users/runner/theos/sdks/
          rm iPhoneOS14.5.sdk.tar.xz

      - name: Compile Tweak
        run: |
          export THEOS=/Users/runner/theos
          make ARCHS="arm64" TARGET="iphone:clang:14.5:14.0" FINALPACKAGE=1
          
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: MyCleanESP
          path: .theos/obj/MyCleanESP.dylib
